import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { drawEffects } from './cards/draw-effects';
import { decodeDeckPortalUrl, type DecodedDeck } from './deck-import/portal-codec';
import { decodeDeckPortalQr } from './deck-import/qr';
import { decodeDeckList } from './deck-import/list';
import { allGroupsSuccess, allReturnMulligan, drawsToReach, filteredSearchSuccess, hypergeometric, targetOnlyKeepMulligan } from './probability/hypergeometric';
import './styles.css';

const percent = (value: number) => `${(value * 100).toFixed(4)}%`;
const number = (value: number) => Number.isFinite(value) ? value : 0;

function NumericInput({ label, value, min, max, onChange }: { label: string; value: number | null; min: number; max: number; onChange(value: number | null): void }) {
  return <label className="field"><span>{label}</span><input type="number" min={min} max={max} value={value ?? ''} onChange={(e) => {
    const next = e.currentTarget.valueAsNumber;
    onChange(Number.isNaN(next) ? null : Math.min(max, Math.max(min, next)));
  }} /></label>;
}

function Simple() {
  const [deck, setDeck] = useState<number | null>(30); const [targets, setTargets] = useState<number | null>(3); const [draws, setDraws] = useState<number | null>(10); const [mulligan, setMulligan] = useState(false);
  const [openSearch, setOpenSearch] = useState(false); const [candidates, setCandidates] = useState(10); const [searchTargets, setSearchTargets] = useState(3); const [searchDraws, setSearchDraws] = useState(1);
  const valid = deck !== null && targets !== null && draws !== null && (!mulligan || deck >= 4);
  const normalizedTargets = valid ? Math.min(targets!, deck!) : 0; const normalizedDraws = valid ? Math.min(draws!, mulligan ? deck! - 4 : deck!) : 0;
  const result = useMemo(() => valid ? (mulligan ? targetOnlyKeepMulligan(deck!, normalizedTargets, normalizedDraws) : hypergeometric(deck!, normalizedTargets, normalizedDraws)) : null, [deck, mulligan, normalizedDraws, normalizedTargets, valid]);
  const curve = useMemo(() => valid && !mulligan ? Array.from({ length: deck! + 1 }, (_, x) => hypergeometric(deck!, normalizedTargets, x).atLeastOne) : [], [deck, mulligan, normalizedTargets, valid]);
  return <main><section className="hero"><p className="eyebrow">SIMPLE</p><h1>すぐにドロー確率を計算</h1><p>現在の山札から、目的カードに到達する確率を厳密計算します。</p></section>
    <section className="panel inputs"><NumericInput label="現在の山札枚数" value={deck} min={mulligan ? 4 : 1} max={40} onChange={setDeck}/><NumericInput label="目的カード残存枚数" value={targets} min={0} max={deck ?? 40} onChange={setTargets}/><NumericInput label="掘る枚数" value={draws} min={0} max={mulligan && deck ? deck - 4 : deck ?? 40} onChange={setDraws}/></section>
    <section className="panel mulligan"><label><input type="checkbox" checked={mulligan} onChange={e => setMulligan(e.currentTarget.checked)}/> マリガンをする（目的カードだけキープ）</label>{mulligan && <p className="assumption">初手4枚を引き、目的カード以外を引き直してから、指定枚数を掘る確率を計算します。</p>}</section>
    {result ? <><section className="result" aria-live="polite"><div><span>1枚以上引く確率</span><strong>{percent(result.atLeastOne)}</strong></div><div><span>期待枚数</span><strong>{result.expected.toFixed(3)} 枚</strong></div><div><span>計算方式</span><strong>厳密計算</strong></div></section><details className="panel"><summary>分布・到達曲線・計算根拠</summary><div className="detail-grid"><div><h2>引ける枚数の分布</h2>{result.exact.map((p, x) => <p key={x}>{x === 3 ? '3枚以上を含む' : `${x}枚`}: <b>{percent(x < 3 ? p : result.exact.slice(3).reduce((a, b) => a + b, 0))}</b></p>)}</div><div><h2>必要な掘る枚数</h2>{mulligan ? <p>マリガン後の到達曲線は、指定枚数の計算結果を表示しています。</p> : <>{[.5,.8,.9].map(t => <p key={t}>{t * 100}% 到達: <b>{drawsToReach(deck!, normalizedTargets, t) ?? '到達不可'} 枚</b></p>)}<div className="curve" aria-label="到達曲線">{curve.map((p, i) => <i key={i} style={{ height: `${p * 100}%` }} title={`${i}枚: ${percent(p)}`}/>)}</div></>}</div></div><p className="assumption">通常ドローは非復元抽出として超幾何分布で計算しています。</p></details></> : <section className="result unavailable" aria-live="polite"><div><span>確率</span><strong>計算不能</strong><p>現在の山札枚数・目的カード残存枚数・掘る枚数をすべて入力してください。</p></div></section>}
    <details className="panel" open={openSearch} onToggle={(e) => setOpenSearch(e.currentTarget.open)}><summary>サーチ設定（任意）</summary><div className="inputs"><NumericInput label="サーチ候補総数" value={candidates} min={0} max={40} onChange={value => setCandidates(value ?? 0)}/><NumericInput label="候補内の目的カード数" value={Math.min(searchTargets,candidates)} min={0} max={candidates} onChange={value => setSearchTargets(value ?? 0)}/><NumericInput label="1回で引く枚数" value={searchDraws} min={1} max={40} onChange={value => setSearchDraws(value ?? 1)}/></div><p>このサーチで1枚以上目的カードを引く確率: <b>{percent(filteredSearchSuccess(candidates, Math.min(searchTargets,candidates), searchDraws))}</b></p><p className="assumption">条件付きサーチは、対象カードを引いた時点で使用可能として計算しています。PP、盤面、進化、カード固有の発動条件を実戦で満たせない場合があるため、実際の到達確率とは異なる可能性があります。</p></details>
  </main>;
}

function Advanced() {
  const [method, setMethod] = useState<'url'|'list'>('url'); const [text, setText] = useState(''); const [message, setMessage] = useState(''); const [deck, setDeck] = useState<DecodedDeck | null>(null);
  const [step, setStep] = useState(1); const [start, setStart] = useState<'game'|'current'>('game'); const [remainingDeck, setRemainingDeck] = useState<number | null>(40); const [draws, setDraws] = useState<number | null>(4);
  const [objective, setObjective] = useState<'any'|'all'>('any'); const [selected, setSelected] = useState<number[]>([]); const [mulligan, setMulligan] = useState('全キープ'); const [enabledEffects, setEnabledEffects] = useState<Record<string, number>>({});
  const importDeck = async () => { try { const decoded = method === 'url' ? await decodeDeckPortalUrl(text) : decodeDeckList(text); setDeck(decoded); setSelected([]); setRemainingDeck(decoded.total); setMessage(`クラス${decoded.classId || '未照合'}・${decoded.format}・${decoded.total}枚のデッキを読み込みました。`); setStep(2); } catch (error) { setDeck(null); setMessage(error instanceof Error ? error.message : '読み込みに失敗しました。'); } };
  const readQr = async (file?: File) => { if (!file) return; try { const url = await decodeDeckPortalQr(file); setMethod('url'); setText(url); setMessage('QRからDeck Portal URLを読み取りました。続けて「読み込む」を押してください。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'QRの読み取りに失敗しました。'); } };
  const activeDeck = start === 'game' ? deck?.total ?? 40 : remainingDeck ?? 0;
  const selectedCards = deck?.cards.filter(card => selected.includes(card.id)) ?? [];
  const selectedCount = selectedCards.reduce((sum, card) => sum + card.quantity, 0);
  const result = deck && selectedCards.length && activeDeck > 0 && draws !== null ? (() => {
    if (start === 'game' && objective === 'any') {
      if (mulligan === '全返し') return allReturnMulligan(deck.total, selectedCount, 0).atLeastOne;
      if (mulligan === '目的カードだけキープ') return targetOnlyKeepMulligan(deck.total, selectedCount, 0).atLeastOne;
    }
    return objective === 'any' ? hypergeometric(activeDeck, Math.min(selectedCount, activeDeck), Math.min(draws, activeDeck)).atLeastOne : allGroupsSuccess(activeDeck, selectedCards.map(card => card.quantity), Math.min(draws, activeDeck));
  })() : null;
  const toggleCard = (id: number) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  return <main><section className="hero"><p className="eyebrow">ADVANCED</p><h1>デッキから詳細に計算</h1><p>複数目的、マリガン、条件付きサーチを段階的に設定します。</p></section><ol className="steps">{['デッキ入力','開始状態','目的条件','マリガン','サーチ設定'].map((x,i)=><li className={step===i+1?'active':''} key={x}>{i+1}. {x}</li>)}</ol>
    <section className="panel" onPaste={event=>{ const file = [...event.clipboardData.files].find(candidate => candidate.type.startsWith('image/')); if (file) { event.preventDefault(); readQr(file); } }}><h2>1. デッキ入力</h2><div className="tabs"><button className={method==='url'?'selected':''} onClick={()=>setMethod('url')}>Deck Portal URL</button><button className={method==='list'?'selected':''} onClick={()=>setMethod('list')}>カード名と枚数</button></div><label className="field qr-input" onDragOver={event=>event.preventDefault()} onDrop={event=>{ event.preventDefault(); readQr(event.dataTransfer.files[0]); }}><span>QRコード画像（選択・ドラッグ＆ドロップ・貼り付け／ブラウザ内で解析）</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>readQr(e.currentTarget.files?.[0])}/></label>{method==='url'?<><label className="field"><span>完全な Deck Portal URL</span><input value={text} placeholder="https://shadowverse-wb.com/ja/deck/detail/?hash=..." onChange={e=>setText(e.target.value)}/></label><p className="hint">生のhash文字列は受け付けません。</p></>:<label className="field"><span>カード名と枚数（1行ずつ）</span><textarea value={text} placeholder={'カード名 3\n別のカード 3'} onChange={e=>setText(e.target.value)}/></label>}<button className="primary" onClick={importDeck}>読み込む</button>{message && <p role="status" className="message">{message}</p>}{deck && <ul className="deck-list">{deck.cards.map(card => <li key={card.id}><span>{card.name}</span><b>×{card.quantity}</b></li>)}</ul>}</section>
    {deck && <><section className="panel"><h2>2. 開始状態</h2><div className="tabs">{[['game','ゲーム開始時'],['current','ゲーム途中']] .map(([value,label])=><button className={start===value?'selected':''} onClick={()=>{setStart(value as 'game'|'current');setStep(2)}} key={value}>{label}</button>)}</div>{start==='game'?<p className="hint">40枚デッキ・初期手札4枚から計算します。</p>:<div className="inputs"><NumericInput label="現在の山札枚数" value={remainingDeck} min={1} max={deck.total} onChange={setRemainingDeck}/><NumericInput label="これから掘る枚数" value={draws} min={0} max={remainingDeck ?? deck.total} onChange={setDraws}/></div>}<button className="primary" onClick={()=>setStep(3)}>目的条件へ</button></section>
    <section className="panel"><h2>3. 目的条件</h2><div className="tabs"><button className={objective==='any'?'selected':''} onClick={()=>setObjective('any')}>いずれかを1枚以上</button><button className={objective==='all'?'selected':''} onClick={()=>setObjective('all')}>すべてを1枚以上</button></div><p className="hint">目的にするカードを選択してください。ゲーム開始時は初手4枚を対象として計算します。</p><div className="target-list">{deck.cards.map(card=><label key={card.id}><input type="checkbox" checked={selected.includes(card.id)} onChange={()=>toggleCard(card.id)}/>{card.name} ×{card.quantity}</label>)}</div>{result !== null&&<section className="result"><div><span>目的達成率</span><strong>{percent(result)}</strong></div><div><span>対象カード</span><strong>{selectedCount} 枚</strong></div><div><span>計算方式</span><strong>厳密計算</strong></div></section>}<button className="primary" onClick={()=>setStep(4)}>マリガンへ</button></section>
    <section className="panel"><h2>4. マリガン</h2><div className="tabs">{['全キープ','全返し','目的カードだけキープ','目的カードとサーチカードをキープ'].map(x=><button className={mulligan===x?'selected':''} onClick={()=>{setMulligan(x);setStep(4)}} key={x}>{x}</button>)}</div><p className="hint">選択中: {mulligan}。ゲーム開始時の「全キープ」「全返し」「目的カードだけキープ」は、単一目的の達成率へ厳密に反映されます。「目的カードとサーチカードをキープ」、カテゴリ上限、セット、ユーザー定義条件は状態エンジン対応後に反映します。</p><button className="primary" onClick={()=>setStep(5)}>サーチ設定へ</button></section>
    <section className="panel"><h2>5. 対応済みサーチ効果（17件）</h2><p className="hint">効果ごとに有効化と使用上限を設定します。PP、盤面、進化、固有条件は成立済みとして扱います。</p><div className="effects">{drawEffects.map(effect=><article key={effect.id}><b>{effect.representative ? `代表${effect.representative} ` : ''}{effect.name}</b><span>{effect.description}</span><label><input type="checkbox" checked={Boolean(enabledEffects[effect.id])} onChange={e=>setEnabledEffects(values=>({...values,[effect.id]:e.currentTarget.checked?1:0}))}/> 有効</label><NumericInput label="上限" value={enabledEffects[effect.id] ?? 0} min={0} max={3} onChange={value=>setEnabledEffects(values=>({...values,[effect.id]:value ?? 0}))}/></article>)}</div><p className="assumption">条件付きサーチは、対象カードを引いた時点で使用可能として計算しています。PP、盤面、進化、カード固有の発動条件を実戦で満たせない場合があるため、実際の到達確率とは異なる可能性があります。</p></section></>}
  </main>;
}

type Page = 'home'|'simple'|'advanced'|'cards'|'guide';
const paths: Record<Page, string> = { home: '/', simple: '/simple', advanced: '/advanced', cards: '/cards', guide: '/guide' };
function pageFromPath(path: string): Page { return (Object.entries(paths).find(([, value]) => value === path)?.[0] as Page | undefined) ?? 'home'; }

function Cards() { return <main><section className="hero"><p className="eyebrow">CARD COVERAGE</p><h1>対応カード一覧</h1><p>確率計算へ有効化できるのは、効果内容を人手で確認した17件です。</p></section><section className="panel"><div className="effects">{drawEffects.map(effect=><article key={effect.id}><b>{effect.representative ? `代表${effect.representative} ` : ''}{effect.name}</b><span>{effect.description}</span><code>{effect.id}</code></article>)}</div></section></main>; }
function Guide() { return <main><section className="hero"><p className="eyebrow">GUIDE</p><h1>使い方・計算上の仮定</h1><p>簡易版では残り山札・対象枚数・掘る枚数を入力します。詳細版ではDeck Portal URL、QR画像、または40枚のカード一覧からデッキを読み込みます。</p></section><section className="panel"><h2>計算方式</h2><p>通常ドローは非復元抽出として超幾何分布で厳密に計算します。複数の目的をすべて満たす確率は包含排除で計算します。</p><p className="assumption">条件付きサーチは、対象カードを引いた時点で使用可能として計算します。PP、盤面、進化、カード固有の発動条件を満たせない実戦では結果が異なる場合があります。</p></section></main>; }

function App() { const [page, setPage] = useState<Page>(() => pageFromPath(window.location.pathname)); const navigate = (next: Page) => { window.history.pushState({}, '', paths[next]); setPage(next); }; useEffect(() => { const listener = () => setPage(pageFromPath(window.location.pathname)); window.addEventListener('popstate', listener); return () => window.removeEventListener('popstate', listener); }, []); return <><header><button className="brand" onClick={()=>navigate('home')}>ドロー確率計算機</button><nav><button onClick={()=>navigate('home')}>ホーム</button><button onClick={()=>navigate('simple')}>簡易版</button><button onClick={()=>navigate('advanced')}>詳細版</button><button onClick={()=>navigate('cards')}>対応カード</button><button onClick={()=>navigate('guide')}>使い方</button></nav></header>{page==='home'&&<main><section className="hero home"><p className="eyebrow">SHADOWVERSE: WORLDS BEYOND</p><h1>欲しいカードを、引ける確率。</h1><p>同じ正確な計算基盤で、すぐ答えを知る簡易版と、デッキを深く検証する詳細版を用意しました。</p><div className="choices"><button onClick={()=>navigate('simple')}><b>簡易版</b><span>残り山札・対象・掘る枚数だけで即計算</span></button><button onClick={()=>navigate('advanced')}><b>詳細版</b><span>デッキ、マリガン、サーチ連鎖を設定</span></button></div></section></main>}{page==='simple'&&<Simple/>}{page==='advanced'&&<Advanced/>}{page==='cards'&&<Cards/>}{page==='guide'&&<Guide/>}<footer>{import.meta.env.VITE_X_URL ? <a href={import.meta.env.VITE_X_URL} target="_blank" rel="noreferrer">X</a> : null}</footer></> }

createRoot(document.getElementById('root')!).render(<App/>);
