import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { drawEffects } from './cards/draw-effects';
import { decodeDeckPortalUrl, type DecodedDeck } from './deck-import/portal-codec';
import { decodeDeckPortalQr } from './deck-import/qr';
import { decodeDeckList } from './deck-import/list';
import { allGroupsSuccess, allReturnMulligan, drawsToReach, filteredSearchSuccess, hypergeometric, targetOnlyKeepMulligan } from './probability/hypergeometric';
import { searchEffectChance } from './probability/search-effect';
import './styles.css';

const percent = (value: number) => `${(value * 100).toFixed(4)}%`;
const number = (value: number) => Number.isFinite(value) ? value : 0;
const classNames: Record<number, string> = { 0: 'ニュートラル', 1: 'エルフ', 2: 'ロイヤル', 3: 'ウィッチ', 4: 'ドラゴン', 5: 'ナイトメア', 6: 'ビショップ', 7: 'ネメシス' };
function emitTelemetry(detail: Record<string, unknown>) { window.dispatchEvent(new CustomEvent('shadowverse:telemetry', { detail })); }

function NumericInput({ label, value, min, max, onChange }: { label: string; value: number | null; min: number; max: number; onChange(value: number | null): void }) {
  return <label className="field"><span>{label}</span><input type="number" min={min} max={max} value={value ?? ''} onChange={(e) => {
    const next = e.currentTarget.valueAsNumber;
    onChange(Number.isNaN(next) ? null : Math.min(max, Math.max(min, next)));
  }} /></label>;
}

function shouldShowSurvey() {
  if (!navigator.language.startsWith('ja')) return false;
  const now = Date.now(); const firstKey = 'draw-calculator:first-calculation'; const shownKey = 'draw-calculator:last-survey';
  if (!localStorage.getItem(firstKey)) { localStorage.setItem(firstKey, String(now)); return false; }
  const lastShown = Number(localStorage.getItem(shownKey) ?? 0);
  if (now - lastShown < 30 * 24 * 60 * 60 * 1000 || Math.random() >= 0.03) return false;
  localStorage.setItem(shownKey, String(now)); return true;
}

function Simple() {
  const [deck, setDeck] = useState<number | null>(40); const [targets, setTargets] = useState<number | null>(3); const [draws, setDraws] = useState<number | null>(10); const [mulligan, setMulligan] = useState(false);
  const [openSearch, setOpenSearch] = useState(false); const [candidates, setCandidates] = useState(10); const [searchTargets, setSearchTargets] = useState(3); const [searchDraws, setSearchDraws] = useState(1);
  const valid = deck !== null && targets !== null && draws !== null && (!mulligan || deck >= 4);
  const normalizedTargets = valid ? Math.min(targets!, deck!) : 0; const normalizedDraws = valid ? Math.min(draws!, mulligan ? deck! - 4 : deck!) : 0;
  const result = useMemo(() => valid ? (mulligan ? targetOnlyKeepMulligan(deck!, normalizedTargets, normalizedDraws) : hypergeometric(deck!, normalizedTargets, normalizedDraws)) : null, [deck, mulligan, normalizedDraws, normalizedTargets, valid]);
  const curve = useMemo(() => valid && !mulligan ? Array.from({ length: deck! + 1 }, (_, x) => hypergeometric(deck!, normalizedTargets, x).atLeastOne) : [], [deck, mulligan, normalizedTargets, valid]);
  return <main><section className="hero"><p className="eyebrow">SIMPLE</p><h1>すぐにドロー確率を計算</h1><p>現在の山札から、目的カードに到達する確率を厳密計算します。</p></section>
    <section className="panel inputs"><NumericInput label="現在の山札枚数" value={deck} min={mulligan ? 4 : 1} max={40} onChange={setDeck}/><NumericInput label="目的カード残存枚数" value={targets} min={0} max={deck ?? 40} onChange={setTargets}/><NumericInput label="掘る枚数" value={draws} min={0} max={mulligan && deck ? deck - 4 : deck ?? 40} onChange={setDraws}/></section>
    <section className="panel mulligan"><label><input type="checkbox" checked={mulligan} onChange={e => setMulligan(e.currentTarget.checked)}/> マリガンをする（目的カードだけキープ）</label>{mulligan && <p className="assumption">初手4枚を引き、目的カード以外を引き直してから、指定枚数を掘る確率を計算します。</p>}</section>
    {result ? <><section className="result" aria-live="polite"><div><span>1枚以上引く確率</span><strong>{percent(result.atLeastOne)}</strong></div><div><span>期待枚数</span><strong>{result.expected.toFixed(3)} 枚</strong></div><div><span>計算方式</span><strong>厳密計算</strong></div></section><details className="panel"><summary>分布・到達曲線</summary><div className="detail-grid"><div><h2>引ける枚数の分布</h2>{result.exact.map((p, x) => <p key={x}>{x === 3 ? '3枚以上を含む' : `${x}枚`}: <b>{percent(x < 3 ? p : result.exact.slice(3).reduce((a, b) => a + b, 0))}</b></p>)}</div><div><h2>必要な掘る枚数</h2>{mulligan ? <p>マリガン後の到達曲線は、指定枚数の計算結果を表示しています。</p> : <>{[.5,.8,.9].map(t => <p key={t}>{t * 100}% 到達: <b>{drawsToReach(deck!, normalizedTargets, t) ?? '到達不可'} 枚</b></p>)}<div className="curve" aria-label="到達曲線">{curve.map((p, i) => <i key={i} style={{ height: `${p * 100}%` }} title={`${i}枚: ${percent(p)}`}/>)}</div></>}</div></div></details></> : <section className="result unavailable" aria-live="polite"><div><span>確率</span><strong>計算不能</strong><p>現在の山札枚数・目的カード残存枚数・掘る枚数をすべて入力してください。</p></div></section>}
    <details className="panel" open={openSearch} onToggle={(e) => setOpenSearch(e.currentTarget.open)}><summary>サーチ設定（任意）</summary><div className="inputs"><NumericInput label="サーチ候補総数" value={candidates} min={0} max={40} onChange={value => setCandidates(value ?? 0)}/><NumericInput label="候補内の目的カード数" value={Math.min(searchTargets,candidates)} min={0} max={candidates} onChange={value => setSearchTargets(value ?? 0)}/><NumericInput label="1回で引く枚数" value={searchDraws} min={1} max={40} onChange={value => setSearchDraws(value ?? 1)}/></div><p>このサーチで1枚以上目的カードを引く確率: <b>{percent(filteredSearchSuccess(candidates, Math.min(searchTargets,candidates), searchDraws))}</b></p><p className="assumption">条件付きサーチは、対象カードを引いた時点で使用可能として計算しています。PP、盤面、進化、カード固有の発動条件を実戦で満たせない場合があるため、実際の到達確率とは異なる可能性があります。</p></details>
  </main>;
}

function Advanced() {
  const [method, setMethod] = useState<'url'|'list'>('url'); const [text, setText] = useState(''); const [message, setMessage] = useState(''); const [deck, setDeck] = useState<DecodedDeck | null>(null);
  const [step, setStep] = useState(1); const [start, setStart] = useState<'game'|'current'>('game'); const [remainingDeck, setRemainingDeck] = useState<number | null>(40); const [draws, setDraws] = useState<number | null>(0);
  const [objective, setObjective] = useState<'any'|'all'>('any'); const [selected, setSelected] = useState<number[]>([]); const [requiredCounts, setRequiredCounts] = useState<Record<number, number>>({}); const [mulligan, setMulligan] = useState('全キープ'); const [enabledEffects, setEnabledEffects] = useState<Record<string, number>>({}); const [calculated, setCalculated] = useState<number | null>(null); const [showSurvey, setShowSurvey] = useState(false);
  const importDeck = async () => { try { const decoded = method === 'url' ? await decodeDeckPortalUrl(text) : decodeDeckList(text); setDeck(decoded); setSelected([]); setRemainingDeck(decoded.total); emitTelemetry({ eventType: 'calculation', classId: decoded.classId, format: decoded.format, cards: decoded.cards.map(card => [card.id, card.quantity]) }); setMessage(`${classNames[decoded.classId] ?? '未照合'}・${decoded.format}・${decoded.total}枚のデッキを読み込みました。`); setStep(2); } catch (error) { setDeck(null); setMessage(error instanceof Error ? error.message : '読み込みに失敗しました。'); } };
  const readQr = async (file?: File) => { if (!file) return; try { const url = await decodeDeckPortalQr(file); setMethod('url'); setText(url); setMessage('QRからDeck Portal URLを読み取りました。続けて「読み込む」を押してください。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'QRの読み取りに失敗しました。'); } };
  const activeDeck = start === 'game' ? deck?.total ?? 40 : remainingDeck ?? 0;
  const effectiveDraws = start === 'game' ? Math.min((draws ?? 0) + 4, activeDeck) : Math.min(draws ?? 0, activeDeck);
  const selectedCards = (deck?.cards.filter(card => selected.includes(card.id)) ?? []).sort((a, b) => (a.cost ?? Number.MAX_SAFE_INTEGER) - (b.cost ?? Number.MAX_SAFE_INTEGER) || a.name.localeCompare(b.name, 'ja'));
  const selectedCount = selectedCards.reduce((sum, card) => sum + card.quantity, 0);
  const result = deck && selectedCards.length && activeDeck > 0 && draws !== null ? (() => {
    const required = selectedCards.map(card => requiredCounts[card.id] ?? 1);
    if (objective === 'any' && selectedCards.length === 1 && required[0] > 1) return hypergeometric(activeDeck, Math.min(selectedCount, activeDeck), effectiveDraws).exact.slice(required[0]).reduce((sum, value) => sum + value, 0);
    if (start === 'game' && objective === 'any') {
      if (mulligan === '全返し') return allReturnMulligan(deck.total, selectedCount, draws ?? 0).atLeastOne;
      if (mulligan === '目的カードだけキープ') return targetOnlyKeepMulligan(deck.total, selectedCount, draws ?? 0).atLeastOne;
    }
    if (start === 'game' && (mulligan === '目的カードとサーチカードをキープ' || mulligan === 'カスタム')) return null;
    return objective === 'any' ? hypergeometric(activeDeck, Math.min(selectedCount, activeDeck), effectiveDraws).atLeastOne : allGroupsSuccess(activeDeck, selectedCards.map(card => card.quantity), effectiveDraws);
  })() : null;
  const toggleCard = (id: number) => setSelected(current => { const next = current.includes(id) ? current.filter(value => value !== id) : [...current, id]; setRequiredCounts(counts => ({ ...counts, [id]: next.includes(id) ? counts[id] ?? 1 : 1 })); return next; });
  return <main><section className="hero"><p className="eyebrow">ADVANCED</p><h1>デッキから詳細に計算</h1><p>デッキ、目的カード、マリガン、サーチ効果を設定して計算します。</p></section>
    <section className="panel" onPaste={event=>{ const file = [...event.clipboardData.files].find(candidate => candidate.type.startsWith('image/')); if (file) { event.preventDefault(); readQr(file); } }}><h2>1. デッキ入力</h2><div className="tabs"><button className={method==='url'?'selected':''} onClick={()=>setMethod('url')}>Deck Portal URL</button><button className={method==='list'?'selected':''} onClick={()=>setMethod('list')}>カード名と枚数</button></div><label className="field qr-input" onDragOver={event=>event.preventDefault()} onDrop={event=>{ event.preventDefault(); readQr(event.dataTransfer.files[0]); }}><span>QRコード画像（選択・ドラッグ＆ドロップ・貼り付け）</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>readQr(e.currentTarget.files?.[0])}/></label>{method==='url'?<label className="field"><span>完全な Deck Portal URL</span><input value={text} placeholder="https://shadowverse-wb.com/ja/deck/detail/?hash=..." onChange={e=>setText(e.target.value)}/></label>:<label className="field"><span>カード名と枚数（1行ずつ）</span><textarea value={text} placeholder={'カード名 3\n別のカード 3'} onChange={e=>setText(e.target.value)}/></label>}<button className="primary" onClick={importDeck}>読み込む</button>{message && <p role="status" className="message">{message}</p>}{deck && <details className="deck-details"><summary>デッキ詳細を表示</summary><ul className="deck-list">{deck.cards.map(card => <li key={card.id}><span>{card.cost ?? '—'} コスト　{card.name}</span><b>×{card.quantity}</b></li>)}</ul></details>}</section>
    {deck && <><section className="panel"><h2>2. 開始状態</h2><div className="tabs">{[['game','ゲーム開始時'],['current','ゲーム途中']].map(([value,label])=><button className={start===value?'selected':''} onClick={()=>setStart(value as 'game'|'current')} key={value}>{label}</button>)}</div>{start==='game'?<div className="inputs"><NumericInput label="マリガン後に追加で引く枚数" value={draws} min={0} max={deck.total - 4} onChange={setDraws}/></div>:<div className="inputs"><NumericInput label="現在の山札枚数" value={remainingDeck} min={1} max={deck.total} onChange={setRemainingDeck}/><NumericInput label="これから掘る枚数" value={draws} min={0} max={remainingDeck ?? deck.total} onChange={setDraws}/></div>}</section>
    <section className="panel"><h2>3. 目的条件</h2><div className="tabs"><button className={objective==='any'?'selected':''} onClick={()=>setObjective('any')}>いずれかを達成</button><button className={objective==='all'?'selected':''} onClick={()=>setObjective('all')}>すべてを達成</button></div><p className="hint">目的カードをコスト順で表示します。選択すると必要枚数を指定できます。</p><div className="target-list">{[...deck.cards].sort((a,b)=>(a.cost ?? Number.MAX_SAFE_INTEGER)-(b.cost ?? Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name,'ja')).map(card=><div className="target-card" key={card.id}><label><input type="checkbox" checked={selected.includes(card.id)} onChange={()=>toggleCard(card.id)}/>{card.cost ?? '—'} コスト　{card.name} ×{card.quantity}</label>{selected.includes(card.id)&&<NumericInput label={`${card.name}の必要枚数`} value={requiredCounts[card.id] ?? 1} min={1} max={card.quantity} onChange={value=>setRequiredCounts(counts=>({...counts,[card.id]:value ?? 1}))}/>}</div>)}</div></section>
    <section className="panel"><h2>4. マリガン</h2><div className="tabs">{['全キープ','全返し','目的カードだけキープ'].map(x=><button className={mulligan===x?'selected':''} onClick={()=>setMulligan(x)} key={x}>{x}</button>)}</div><p className="hint">ゲーム開始時の単一目的では、選択したマリガンを厳密計算します。</p></section>
    <section className="panel"><h2>5. サーチ効果</h2><p className="hint">読み込んだデッキに含まれるカードの効果だけを表示します。</p><div className="effects">{drawEffects.filter(effect=>deck.cards.some(card=>card.id===effect.cardId)).map(effect=>{ const chance = searchEffectChance(deck.cards, selected, effect, enabledEffects[effect.id] ?? 0); return <article key={effect.id}><b>{effect.name}</b><span>{effect.description}{selected.length ? `／候補${chance.candidates}枚・目的${chance.targetCandidates}枚` : ''}</span><label><input type="checkbox" checked={Boolean(enabledEffects[effect.id])} onChange={e=>setEnabledEffects(values=>({...values,[effect.id]:e.currentTarget.checked?1:0}))}/> 有効</label><NumericInput label="使用回数" value={enabledEffects[effect.id] ?? 0} min={0} max={3} onChange={value=>setEnabledEffects(values=>({...values,[effect.id]:value ?? 0}))}/></article>})}</div></section>
    <section className="panel"><h2>6. 計算結果</h2><button className="primary" disabled={result===null} onClick={()=>{ setCalculated(result); setShowSurvey(shouldShowSurvey()); }}>計算</button>{calculated !== null ? <><section className="result"><div><span>目的達成率</span><strong>{percent(calculated)}</strong></div><div><span>対象カード</span><strong>{selectedCount} 枚</strong></div><div><span>計算方式</span><strong>厳密計算</strong></div></section><details className="panel"><summary>分布・到達曲線</summary><div className="detail-grid"><div><h3>引ける枚数の分布</h3>{hypergeometric(activeDeck, Math.min(selectedCount, activeDeck), effectiveDraws).exact.map((value,index)=><p key={index}>{index}枚: <b>{percent(value)}</b></p>)}</div><div><h3>到達曲線</h3><div className="curve">{Array.from({length:activeDeck+1},(_,count)=>hypergeometric(activeDeck,Math.min(selectedCount,activeDeck),count).atLeastOne).map((value,index)=><i key={index} style={{height:`${value*100}%`}} title={`${index}枚: ${percent(value)}`}/>)}</div></div></div></details>{showSurvey&&<section className="panel survey"><h3>任意アンケート</h3><p className="hint">今後の改善のため、よろしければ教えてください。</p><label className="field"><span>使用頻度</span><select defaultValue=""><option value="">回答しない</option><option>初回</option><option>月1未満</option><option>月1〜3</option><option>週1〜2</option><option>週3以上</option><option>ほぼ毎日</option></select></label><button onClick={()=>setShowSurvey(false)}>閉じる</button></section>}</> : <p className="hint">目的条件を選択してから「計算」を押してください。</p>}</section></>}
  </main>;
}

type Page = 'home'|'simple'|'advanced';
const paths: Record<Page, string> = { home: '/', simple: '/simple', advanced: '/advanced' };
function pageFromPath(path: string): Page { return (Object.entries(paths).find(([, value]) => value === path)?.[0] as Page | undefined) ?? 'home'; }

function App() { const [page, setPage] = useState<Page>(() => pageFromPath(window.location.pathname)); const navigate = (next: Page) => { window.history.pushState({}, '', paths[next]); setPage(next); }; useEffect(() => { const listener = () => setPage(pageFromPath(window.location.pathname)); window.addEventListener('popstate', listener); return () => window.removeEventListener('popstate', listener); }, []); return <><header><button className="brand" onClick={()=>navigate('home')}>ドロー確率計算機</button><nav><button onClick={()=>navigate('home')}>ホーム</button><button onClick={()=>navigate('simple')}>簡易版</button><button onClick={()=>navigate('advanced')}>詳細版</button></nav></header>{page==='home'&&<main><section className="hero home"><p className="eyebrow">SHADOWVERSE: WORLDS BEYOND</p><h1>欲しいカードを、引ける確率。</h1><p>同じ正確な計算基盤で、すぐ答えを知る簡易版と、デッキを深く検証する詳細版を用意しました。</p><div className="choices"><button onClick={()=>navigate('simple')}><b>簡易版</b><span>残り山札・対象・掘る枚数だけで即計算</span></button><button onClick={()=>navigate('advanced')}><b>詳細版</b><span>デッキ、マリガン、サーチ連鎖を設定</span></button></div></section></main>}{page==='simple'&&<Simple/>}{page==='advanced'&&<Advanced/>}<footer>{import.meta.env.VITE_X_URL ? <a href={import.meta.env.VITE_X_URL} target="_blank" rel="noreferrer">X</a> : null}</footer></> }

createRoot(document.getElementById('root')!).render(<App/>);
